name: e2e
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  e2e-tests:
    strategy:
      matrix:
        parallel-id: [0, 1, 2, 3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.16'
      - run: make e2e-local E2E_TEST_CHUNK=${{ matrix.parallel-id }} E2E_TEST_NUM_CHUNKS=${{ strategy.job-total }} E2E_NODES=2 ARTIFACTS_DIR=./artifacts-${{ matrix.parallel-id }}/
      - name: Archive Test Artifacts # test results, failed or not, are always uploaded.
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-output-${{ (github.event.pull_request.head.sha || github.sha) }}-${{ github.run_id }}
          path: ${{ github.workspace }}/bin/artifacts-${{ github.run_id }}/*
